### ISSUE TITLE
hyprcursors don't scale higher than 24.

### ISSUE THREAD

**Issue by aljustiet** [catppuccin/cursors#36] opened 2024-09-21 22:29 UTC
When I change the cursor size using the `hyprctl setcursor catppuccin-frappe-sapphire 32`, it doesn't apply. Here's the [demo](https://files.catbox.moe/44v4ve.mp4).x
Version: 0.3.1
Package [source](https://aur.archlinux.org/packages/catppuccin-cursors-frappe)

**Comment by sgoudham** [comment] 2024-10-20 20:15
Closing as this is effectively a duplicate of #31

**Closed by sgoudham** 2024-10-20 20:15 UTC
Labels: hyprland
