### ISSUE TITLE
hyprcursor should pack SVG, not PNG

### ISSUE THREAD

**Issue by jinliu** [catppuccin/cursors#49] opened 2024-10-25 14:47 UTC
We shouldn't build hyprcursor from XCursor files, but from our SVG files.

I can make a PR for this.

**Comment by sgoudham** [comment] 2024-10-25 14:48
I believe this is a duplicate of #31 since there is some context there about why PNGs are currently used. 

I'd encourage you to read that issue and comment on there for any fixes to hyperland

**Closed by sgoudham** 2024-10-25 14:48 UTC
